#!/bin/bash
# k8s cluster bird view plugins
# usage: kubectl bv

echo "Kuber cluster bird view"
echo "======Node======"
kubectl get node -o wide
echo
echo "======Service======"
kubectl get service -o wide  --all-namespaces
echo
echo "======Deployment======"
kubectl get deployment -o wide --all-namespaces
echo
echo "======Pod======"
kubectl get po -o wide --all-namespaces 
echo
echo "======Plugin======"
kubectl plugin list